### ISSUE TITLE
rendering of images in cat flatmap

### ISSUE THREAD

**Issue by keeran97** [AnatomicMaps/flatmap-maker#20] opened 2022-10-20 22:14 UTC
there is an issue with missing images. i have tried generating the cat flatmap with an SVG exported both from AI and boxy. these missing images occurs in both cases. and in both cases I have run `degroup,py` beforehand. the paths are closed. these are with the latest files on the `keerans_changes` branch of the cat-flatmap repo

![Screenshot 2022-10-21 111051](https://user-images.githubusercontent.com/85910337/197069142-1cfcb5df-43ed-48eb-863d-a8a0977bba27.jpg)

**Comment by dbrnz** [comment] 2022-10-21 00:26
What shows when you view the SVG as initially exported from AI?

**Comment by keeran97** [comment] 2022-10-21 00:41
as in the first export, before it is opened and edited in boxy? the same case - images are still missing
![image](https://user-images.githubusercontent.com/85910337/197085246-17a00b82-2176-4acd-9ffb-52faf2855091.png)

**Comment by dbrnz** [comment] 2022-10-21 01:02
So if this is the SVG as seen in Chrome, and AI shows the images, the problem is in Illustrator's SVG export, something we can do nothing directly about.

The "fix" is to use Boxy's composition tool to cut-and-paste the image back.

**Comment by dbrnz** [comment] 2022-10-21 01:02
Closing as this is not a mapmaker issue.

**Comment by dbrnz** [comment] 2022-10-28 02:27
@keeran97 unless you can clearly demonstrate that a filled feature on an SVG doesn't show in a map generated using `--background-tiles` then there isn't an issue in mapmaker.

**Comment by dbrnz** [comment] 2022-10-28 02:33
@keeran97 my apologies -- I assumed one of the above screenshots was showing no fill in Chrome, hence didn't check myself. I now confirm that Chrome does show fill -- we have a mapmaker bug!

**Comment by keeran97** [comment] 2022-10-28 05:54
no worries, i may not have made it clear that in the SVG editor the image is present and things looks fine. but in the generated map the image fills are absent. let me know if there's anything else I can do.

**Comment by dbrnz** [comment] 2022-10-30 09:06
Fixed with commit e9a8ef9.

**Closed by dbrnz** 2022-10-30 09:06 UTC
